name: jargon_onRelease

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Annotated tag name'
        required: true
      message:
        description: 'Annotated tag message'
        required: true
  repository_dispatch:
    types: [ 'jargon_onRelease' ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.url }}"'
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.fileName }}"'
      - run: 'echo "field: ${{ github.event.client_payload.release.version }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'


  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.url }}"'
      - run: 'echo "field: ${{ github.event.client_payload.artefacts.jsonldVocab.fileName }}"'
      - run: 'wget -O transport.jsonld ${{ github.event.client_payload.artefacts.jsonldVocab.url }}'
      - run: 'mv transport.jsonld vocab/'
      - run: java -jar vocab-jsonld-merge-1.0.0.jar
      - run: 'mv merged.jsonld vocab/'
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vocab
          git commit -m "release: ${{ github.event.client_payload.release.version }}"
          git push origin main
          git tag -a ${{ github.event.client_payload.release.version }} -m "release: ${{ github.event.client_payload.release.version }}"
          git push origin ${{ github.event.client_payload.release.version }}

  package:
    needs:
      - create_tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.client_payload.release.version }}

      - name: create artifact tar
        run: |
          tar -cvzf vocabulary.tar.gz vocab/transport.jsonld 

      - name: upload build details
        uses: actions/upload-artifact@v3
        with:
          name: vocabulary_artifact
          path: vocabulary.tar.gz

  release_tag:
    needs:
      - package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ github.event.client_payload.release.version }}

      - name: Get vocabulary
        uses: actions/download-artifact@v3
        with:
          name: vocabulary_artifact
          path: ./

      - name: extract artifact
        run: |
          tar -zxvf vocabulary.tar.gz

      - name: Create Releases
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.client_payload.release.version }}
          artifacts: 'vocab/*.jsonld'
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.PAT_TOKEN }}
#          repository: uncefact/vocabulary-outputs
#          event-type: update-transport
